/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BRAZE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SNOWFLAKE_ACCOUNT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SNOWFLAKE_DATABASE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SNOWFLAKE_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SNOWFLAKE_SCHEMA": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SNOWFLAKE_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SNOWFLAKE_WAREHOUSE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "braze-mau-tracker": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "data": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "demo": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "sdk": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "snowflake-processor": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}